# -*- coding: utf-8 -*-
"""GREEDY BEST FIRST SEARCH

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAwk3qMSp402hHIM0cbe0fJxDysc7Ws6

GREEDY BEST FIRST SEARCH
"""

from queue import PriorityQueue

# Fungsi untuk merekonstruksi jalur
def reconstruct_path(came_from, start, goal):
    current = goal
    path = []

    while current != start:
        path.append(current)
        current = came_from[current]

    path.append(start)
    path.reverse()
    return path

# Fungsi algoritma Greedy Best-First Search
def greedy_search(graph, start, goal, heuristic):
    frontier = PriorityQueue()
    frontier.put((heuristic[start], start))
    came_from = {}
    explored = set()

    while not frontier.empty():
        _, current_node = frontier.get()

        if current_node == goal:
            print("Simpul tujuan ditemukan!")
            path = reconstruct_path(came_from, start, goal)
            print("Jalur terpendek:", path)
            return path

        explored.add(current_node)

        for neighbor, cost in graph[current_node].items():
            if neighbor not in explored and neighbor not in came_from:
                frontier.put((heuristic[neighbor], neighbor))
                came_from[neighbor] = current_node

    print("Simpul tujuan tidak ditemukan!")
    return None

# Daftar heuristik sesuai gambar
heuristic = {
    'S': 6,
    'A': 4,
    'B': 3,
    'C': 3,
    'D': 1,
    'G': 0
}

# Graf sesuai dengan gambar (menggunakan dictionary adjacency dengan bobot)
graph = {
    'S': {'A': 3, 'B': 2},
    'A': {'B': 1, 'D': 5},
    'B': {'C': 2},
    'C': {'G': 4},
    'D': {'G': 1, 'C': 3},
}

# Titik awal dan tujuan
start_node = 'S'
goal_node = 'G'

# Panggil fungsi Greedy Best-First Search
greedy_search(graph, start_node, goal_node, heuristic)